#pragma config(Sensor, dgtl1,  Lift,           sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           liftL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DDL,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DML,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           chainbar,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DMR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DDR,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftR,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  bStopTasksBetweenModes = true;

}

task autonomous()
{
}
task usercontrol()
{
	int holdHeight = 0;
  while (true)
  {
  	if(abs(vexRT[Ch3]) > 15){
  		motor[DDL] = vexRT[Ch3];
  		motor[DML] = vexRT[Ch3];
  	}
  	else{
  		motor[DDL] = 0;
  		motor[DML] = 0;
  	}
  	if(abs(vexRT[Ch2]) > 15){
  		motor[DDR] = vexRT[Ch2];
  		motor[DMR] = vexRT[Ch2];
  	}
  	else{
  		motor[DDR] = 0;
  		motor[DMR] = 0;
  	}



  	if(vexRT[Btn7U]){
  		motor[mogo] = 127;
  //		motor[mogoR] = 127;
  	}
  	else if(vexRT[Btn7D]){
  		motor[mogo] = -127;
  	//	motor[mogoR] = -127;
  	}
  	else{
  		motor[mogo] = 0;
  		//motor[mogoR] = 0;
  	}
  	  	if(vexRT[Btn7U]){
  		motor[mogo] = 127;
  //		motor[mogoR] = 127;
  	}
  	else if(vexRT[Btn7D]){
  		motor[mogo] = -127;
  	//	motor[mogoR] = -127;
  	}
  	else{
  		motor[mogo] = 0;
  		//motor[mogoR] = 0;
  	}


  	if(vexRT[Btn8U]){
  		motor[chainbar] = 127;
  	}
  	else if(vexRT[Btn8D]){
  		motor[chainbar] = -127;
  	}
  	else{
  		motor[chainbar] = 0;
  	}


  	if(vexRT[Btn6U]){
  		motor[liftL] = 127;
  		motor[liftR] = 127;
  		holdHeight = SensorValue[Lift];
  	}
  	else if(vexRT[Btn6D]){
  		motor[liftL] = -127;
  		motor[liftR] = -127;
  		holdHeight = SensorValue[Lift];
  	}
  	else{
  	  int errorH = 0;
    	int kP = 2;
    	errorH = holdHeight - SensorValue[Lift];

   	 	motor[liftR] = errorH * kP;
   		motor[liftL] = errorH * kP;
   	}




  	wait1Msec(15);
  }
}
