#pragma config(Motor,  port2,           LLU,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LLD,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// LLU is Left Lift Up
// LLD is Left Lift Down
task main()
{
	while(true){
		if(vexRT[Btn5U]){
			motor[LLU] = 127;
			motor[LLD] = 127;
		}
		else if(vexRT[Btn5D]){
			motor[LLU] = -127;
			motor[LLD] = -127;
		}
		else{
			motor[LLU] = 0;
			motor[LLD] = 0;
		}
	}


}
