#pragma config(Motor,  port1,           pt1,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(vexRT[Btn5D]){
			motor[pt1] = 127;
		}
	}


}
