#pragma config(Sensor, dgtl1,  d1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  d3,             sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  d5,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  d7,             sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  d9,             sensorQuadEncoder)
#pragma config(Sensor, dgtl11, d11,            sensorQuadEncoder)
#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           m9,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          m10,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(true){
		if(vexRT[Ch3]){
			motor[m1] = 127;
			motor[m2] = 127;
			motor[m3] = 127;
			motor[m4] = 127;
			motor[m5] = 127;
			motor[m6] = 127;
			motor[m7] = 127;
			motor[m8] = 127;
			motor[m9] = 127;
			motor[m10] = 127;
		}
		else if(vexRT[Ch3]){
			motor[m1] = -127;
			motor[m2] = -127;
			motor[m3] = -127;
			motor[m4] = -127;
			motor[m5] = -127;
			motor[m6] = -127;
			motor[m7] = -127;
			motor[m8] = -127;
			motor[m9] = -127;
			motor[m10] = -127;
		}
		else{
			motor[m1] = 0;
			motor[m2] = 0;
			motor[m3] = 0;
			motor[m4] = 0;
			motor[m5] = 0;
			motor[m6] = 0;
			motor[m7] = 0;
			motor[m8] = 0;
			motor[m9] = 0;
			motor[m10] = 0;
		}
	}


}
